name: dart.ttyd
description: now creating..
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:

dev_dependencies:
  build_web_compilers: '>=1.2.0 <3.0.0'
  build_runner: '>=1.3.0 <2.0.0'
